name: Jest
on:
  pull_request:
    branches:
      - dev
env:
  NEXT_PUBLIC_KAKAO_LOGIN: ${{ secrets.TEST_KAKAO }}
  NEXT_PUBLIC_NAVER_LOGIN: ${{ secrets.TEST_NAVER }}
  NEXT_PUBLIC_GOOGLE_LOGIN: ${{ secrets.TEST_GOOGLE }}
  NEXT_PUBLIC_API_URL: ${{ secrets.TEST_API_URL }}
jobs:
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install unplugged dependencies
        run: yarn install
      - name: Run All Jest Tests and Collect Coverage
        run: yarn test:ci --coverage
      - name: Upload Coverage To CodeCov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
