name: Storybook
on:
  pull_request:
    branches:
      - dev
env:
  NEXT_PUBLIC_API_URL: ''
  NEXT_PUBLIC_REMOTE_IMAGE_URL: ''
jobs:
  storybook:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'storybook') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: yarn
      - name: Build Storybook
        run: yarn run build-storybook
      - name: chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          workingDir: ./
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.SECRET_TOKEN }}
      - name: comment to Pull Request
        uses: thollander/actions-comment-pull-request@v1
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
        with:
          message: 'storybook deployed!!!: ${{ steps.chromatic.outputs.storybookUrl }}'
